import '../../domain/model/game_card.dart';

abstract class KCards {
  static const List<GameCard> all = [
    GameCard(id: '01', name: 'Albert Einstein'),
    GameCard(id: '02', name: 'Michael Jackson'),
    GameCard(id: '03', name: 'Lionel Messi'),
    GameCard(id: '04', name: 'Marilyn Monroe'),
    GameCard(id: '05', name: 'Napoleon Bonaparte'),
    GameCard(id: '06', name: 'Walt Disney'),
    GameCard(id: '07', name: 'Frida Kahlo'),
    GameCard(id: '08', name: 'Cristiano Ronaldo'),
    GameCard(id: '09', name: 'Leonardo da Vinci'),
    GameCard(id: '10', name: 'Shakira'),
    GameCard(id: '11', name: 'Charlie Chaplin'),
    GameCard(id: '12', name: 'Cleopatra'),
    GameCard(id: '13', name: 'Elvis Presley'),
    GameCard(id: '14', name: 'Marie Curie'),
    GameCard(id: '15', name: 'Julio César'),
    GameCard(id: '16', name: 'Harry Potter'),
    GameCard(id: '17', name: 'Sherlock Holmes'),
    GameCard(id: '18', name: 'Indiana Jones'),
    GameCard(id: '19', name: 'James Bond'),
    GameCard(id: '20', name: 'Robin Hood'),
    GameCard(id: '21', name: 'Spiderman'),
    GameCard(id: '22', name: 'Batman'),
    GameCard(id: '23', name: 'Superman'),
    GameCard(id: '24', name: 'Darth Vader'),
    GameCard(id: '25', name: 'Yoda'),
    GameCard(id: '26', name: 'Gandalf'),
    GameCard(id: '27', name: 'Hermione Granger'),
    GameCard(id: '28', name: 'Simba'),
    GameCard(id: '29', name: 'Shrek'),
    GameCard(id: '30', name: 'Drácula'),
    GameCard(id: '31', name: 'Frankenstein'),
    GameCard(id: '32', name: 'Romeo y Julieta'),
    GameCard(id: '33', name: 'Don Quijote'),
    GameCard(id: '34', name: 'Mona Lisa'),
    GameCard(id: '35', name: 'Newton'),
    GameCard(id: '36', name: 'Shakespeare'),
    GameCard(id: '37', name: 'Beethoven'),
    GameCard(id: '38', name: 'Mozart'),
    GameCard(id: '39', name: 'Picasso'),
    GameCard(id: '40', name: 'Diego Maradona'),
    GameCard(id: '41', name: 'Usain Bolt'),
    GameCard(id: '42', name: 'Muhammad Ali'),
    GameCard(id: '43', name: 'Serena Williams'),
    GameCard(id: '44', name: 'Pelé'),
    GameCard(id: '45', name: 'Freddie Mercury'),
    GameCard(id: '46', name: 'Madonna'),
    GameCard(id: '47', name: 'Lady Gaga'),
    GameCard(id: '48', name: 'Bob Marley'),
    GameCard(id: '49', name: 'Steve Jobs'),
    GameCard(id: '50', name: 'Elon Musk'),
  ];
}
